blank_issues_enabled: true
contact_links:
  - name: Fosscord Documentation
    url: https://docs.fosscord.com/
    about: Need documentation and examples for the Fosscord? Head over to Fosscord's official documentation.
  - name: Discord's Developer Documentation
    url: https://discord.com/developers/docs/intro
    about: Need help with the Discord resources? Head here instead of asking on Fosscord!
  - name: Fosscord' Official Discord server
    url: https://discord.com/invite/Ms5Ev7S6bF
    about: Need help with the server? Talk with us in our official server.
